<div class="container-fluid pt-3">
    <div class="d-flex justify-content-between align-items-center flex-wrap mb-3">
        <div><h4 class="mb-0">Diagnostik Spike Performa</h4><small class="text-muted">Insiden CPU ≥60% untuk MySQL, Forbes, dan Sec-Forbes. Evidence disimpan 30 hari.</small></div>
        <div><a class="btn btn-outline-secondary btn-sm" href="<?= base_url() ?>endorse/queue-diagnostics">Diagnostik Queue</a></div>
    </div>
    <div class="card p-3 mb-3"><div class="d-flex gap-2 align-items-center"><label class="mb-0">Rentang</label><select id="spikeRange" class="form-control form-control-sm" style="max-width:160px"><option value="24h">24 jam</option><option value="7d">7 hari</option><option value="30d">30 hari</option></select><button id="spikeReload" class="btn btn-primary btn-sm">Refresh</button></div></div>
    <div id="spikeAlert"></div><div class="row mb-3" id="spikeCards"></div>
    <div class="row"><div class="col-lg-4"><div class="card p-3 mb-3"><h6>Per Service</h6><div class="table-responsive"><table class="table table-sm" id="spikeServices"><thead><tr><th>Service</th><th>Insiden</th><th>Peak CPU</th><th>Rata-rata</th></tr></thead><tbody></tbody></table></div></div></div><div class="col-lg-8"><div class="card p-3 mb-3"><h6>Timeline Insiden</h6><div class="table-responsive"><table class="table table-sm" id="spikeIncidents"><thead><tr><th>Mulai</th><th>Service</th><th>Status</th><th>Durasi</th><th>Peak CPU</th><th>Request</th><th>User aktif</th><th></th></tr></thead><tbody></tbody></table></div></div></div></div>
</div>
<div class="modal fade" id="spikeDetailModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Evidence Insiden</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="spikeDetailBody"></div></div></div></div>
<script>
(function(){
 const base='<?= base_url() ?>', esc=s=>$('<div>').text(s==null?'':String(s)).html(); let modal;
 const sec=n=>n==null?'-':(Number(n)<60?Number(n).toFixed(0)+' dtk':(Number(n)/60).toFixed(1)+' mnt');
 function rows(sel,list,fn,empty){ $(sel+' tbody').html(list.length?list.map(fn).join(''):'<tr><td colspan="10" class="text-muted">'+empty+'</td></tr>'); }
 function load(){ const range=$('#spikeRange').val(); $.getJSON(base+'endorse/performance-spikes-data',{range}).done(d=>{ if(!d.ready){ $('#spikeAlert').html('<div class="alert alert-warning">'+esc(d.message||'Data belum siap.')+'</div>'); return; } const s=d.summary||{}; const cards=[['Insiden',s.incidents||0],['Masih terbuka',s.open_incidents||0],['Peak CPU',s.peak_cpu_percent==null?'-':Number(s.peak_cpu_percent).toFixed(1)+'%'],['Durasi rata-rata',sec(s.average_duration_seconds)],['Request pada evidence',s.request_count||0],['User aktif',s.active_user_count||0]]; $('#spikeCards').html(cards.map(x=>'<div class="col-md-4 col-xl-2 mb-2"><div class="card p-3"><small class="text-muted">'+x[0]+'</small><strong class="fs-4">'+esc(x[1])+'</strong></div></div>').join('')); rows('#spikeServices',d.by_service||[],x=>'<tr><td>'+esc(x.service_name)+'</td><td>'+x.incidents+'</td><td>'+esc(x.peak_cpu_percent)+'%</td><td>'+sec(x.average_duration_seconds)+'</td></tr>','Belum ada insiden.'); rows('#spikeIncidents',d.incidents||[],x=>'<tr><td>'+esc(x.started_at)+'</td><td>'+esc(x.service_name)+'</td><td>'+esc(x.status)+'</td><td>'+sec(x.duration_seconds)+'</td><td>'+esc(x.peak_cpu_percent)+'%</td><td>'+x.request_count+'</td><td>'+x.active_user_count+'</td><td><a href="#" class="spike-detail" data-id="'+x.id+'">Detail</a></td></tr>','Belum ada insiden.'); }).fail(()=>$('#spikeAlert').html('<div class="alert alert-danger">Gagal mengambil data diagnostik.</div>')); }
 $(document).on('click','.spike-detail',function(e){ e.preventDefault(); $.getJSON(base+'endorse/performance-spikes-detail',{id:$(this).data('id')}).done(d=>{ const i=d.incident||{}, endpoints=typeof i.endpoint_summary_json==='string'?JSON.parse(i.endpoint_summary_json||'[]'):i.endpoint_summary_json||[]; const summary=typeof i.summary_json==='string'?JSON.parse(i.summary_json||'{}'):i.summary_json||{}; const evidence=(d.evidence||[]).map(x=>{let v=typeof x.evidence_json==='string'?JSON.parse(x.evidence_json||'{}'):x.evidence_json||{}; return '<h6>'+esc(x.phase)+' · '+esc(x.captured_at)+'</h6><p><strong>MySQL evidence:</strong> '+(v.mysql_diagnostics?'tersedia':'tidak tersedia')+' · <strong>PERF:</strong> '+((v.request_performance||[]).length)+' request</p>';}).join(''); const h='<p><strong>'+esc(i.service_name)+'</strong> · '+esc(i.started_at)+' · peak '+esc(i.peak_cpu_percent)+'%</p><h6>Delta counter MySQL</h6><pre class="small bg-light p-2">'+esc(JSON.stringify(summary.mysql_counter_delta||{},null,2))+'</pre><h6>Endpoint terberat</h6><table class="table table-sm"><thead><tr><th>Service</th><th>Endpoint</th><th>Request</th><th>Total</th><th>Max</th><th>DB</th></tr></thead><tbody>'+endpoints.map(x=>'<tr><td>'+esc(x.service)+'</td><td>'+esc(x.route)+'</td><td>'+x.requests+'</td><td>'+esc(x.total_ms)+'ms</td><td>'+esc(x.max_ms)+'ms</td><td>'+esc(x.db_ms)+'ms</td></tr>').join('')+'</tbody></table><h6>Sample CPU</h6><pre class="small bg-light p-2">'+esc(JSON.stringify(d.samples||[],null,2))+'</pre>'+evidence; $('#spikeDetailBody').html(h); if(!modal)modal=new bootstrap.Modal(document.getElementById('spikeDetailModal')); modal.show(); }); });
 $('#spikeReload,#spikeRange').on('click change',load); load();
})();
</script>
