<div class="container-fluid pt-3">
    <div class="d-flex justify-content-between align-items-center flex-wrap mb-3">
        <div><h4 class="mb-0">Diagnostik Refresh Endorse</h4><small class="text-muted">Bukti 30 hari untuk mencari duplicate queue, retry, dan spike resource.</small></div>
        <div><a class="btn btn-outline-secondary btn-sm" href="<?= base_url() ?>endorse/queue">Kembali ke Antrian</a></div>
    </div>
    <div class="card p-3 mb-3"><div class="d-flex gap-2 align-items-center"><label class="mb-0">Rentang</label><select id="diagRange" class="form-control form-control-sm" style="max-width:160px"><option value="24h">24 jam</option><option value="7d">7 hari</option><option value="30d">30 hari</option></select><button id="diagReload" class="btn btn-primary btn-sm">Refresh</button></div></div>
    <div id="diagSignals"></div>
    <div class="row mb-3" id="diagCards"></div>
    <div class="row"><div class="col-lg-6"><div class="card p-3 mb-3"><h6>Aktivitas Harian</h6><div class="table-responsive"><table class="table table-sm" id="diagDaily"><thead><tr><th>Tanggal</th><th>Queue</th><th>Unik</th><th>Selesai</th><th>Gagal</th></tr></thead><tbody></tbody></table></div></div></div><div class="col-lg-6"><div class="card p-3 mb-3"><h6>Error Attempt</h6><div class="table-responsive"><table class="table table-sm" id="diagErrors"><thead><tr><th>Kelas</th><th>Status</th><th>Attempt</th></tr></thead><tbody></tbody></table></div></div></div></div>
    <div class="card p-3 mb-3"><h6>Run Queue Terbaru</h6><div class="table-responsive"><table class="table table-sm" id="diagRuns"><thead><tr><th>Waktu</th><th>Sumber</th><th>Kandidat</th><th>Masuk</th><th>Skip</th><th>Selesai</th><th>Retry</th><th>Gagal</th><th></th></tr></thead><tbody></tbody></table></div></div>
    <div class="card p-3"><h6>Spike Resource</h6><div class="table-responsive"><table class="table table-sm" id="diagSpikes"><thead><tr><th>Waktu</th><th>Sumber</th><th>Level</th><th>Ringkasan</th></tr></thead><tbody></tbody></table></div></div>
</div>
<div class="modal fade" id="diagRunModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Lineage Run</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="diagRunBody"></div></div></div></div>
<script>
(function(){
 const base='<?= base_url() ?>', esc=s=>$('<div>').text(s==null?'':String(s)).html(); let modal=null;
 function cards(s,rate,res){ const values=[['Queue row',s.queue_rows||0],['Scope unik',s.unique_scopes||0],['Duplicate rate',(rate||0)+'%'],['Selesai',s.completed||0],['Gagal',s.failed||0],['MySQL CPU terakhir',res.length?Number(res[res.length-1].mysql_cpu_percent||0).toFixed(1)+'%':'-']]; $('#diagCards').html(values.map(x=>'<div class="col-md-4 col-xl-2 mb-2"><div class="card p-3"><small class="text-muted">'+x[0]+'</small><strong class="fs-4">'+esc(x[1])+'</strong></div></div>').join('')); }
 function rows(sel,list,fn,empty){ $(sel+' tbody').html(list.length?list.map(fn).join(''):'<tr><td colspan="10" class="text-muted">'+empty+'</td></tr>'); }
 function load(){ const range=$('#diagRange').val(); $.getJSON(base+'endorse/queue-diagnostics-data',{range}).done(d=>{ cards(d.summary||{},d.duplicate_rate,d.resources||[]); $('#diagSignals').html((d.signals||[]).map(x=>'<div class="alert alert-'+(x.level==='ok'?'success':'danger')+' py-2">'+esc(x.message)+'</div>').join('')); rows('#diagDaily',d.daily||[],x=>'<tr><td>'+esc(x.day)+'</td><td>'+x.queue_rows+'</td><td>'+x.unique_scopes+'</td><td>'+x.completed+'</td><td>'+x.failed+'</td></tr>','Belum ada histori.'); rows('#diagErrors',d.errors||[],x=>'<tr><td>'+esc(x.error_class)+'</td><td>'+esc(x.status)+'</td><td>'+x.attempts+'</td></tr>','Belum ada attempt.'); rows('#diagRuns',d.runs||[],x=>'<tr><td>'+esc(x.started_at)+'</td><td>'+esc(x.source)+'</td><td>'+x.candidate_count+'</td><td>'+x.enqueued_count+'</td><td>'+x.skipped_duplicate_count+'</td><td>'+x.completed_count+'</td><td>'+x.retrying_count+'</td><td>'+x.failed_count+'</td><td><a href="#" class="diag-run" data-id="'+esc(x.id)+'">Detail</a></td></tr>','Belum ada run.'); rows('#diagSpikes',d.spikes||[],x=>'<tr><td>'+esc(x.captured_at)+'</td><td>'+esc(x.source)+'</td><td>'+esc(x.severity)+'</td><td>'+esc(x.summary)+'</td></tr>','Belum ada spike yang tersimpan.'); }).fail(()=>$('#diagSignals').html('<div class="alert alert-danger">Gagal mengambil data diagnostik.</div>')); }
 $(document).on('click','.diag-run',function(e){ e.preventDefault(); $.getJSON(base+'endorse/queue-diagnostics-run',{id:$(this).data('id')}).done(d=>{ let r=d.run||{}; let h='<p><strong>'+esc(r.source)+'</strong> · '+esc(r.started_at)+' · '+esc(r.note||'')+'</p><table class="table table-sm"><thead><tr><th>Scope</th><th>Platform</th><th>Status</th><th>Attempt</th><th>Waktu</th><th>Error</th></tr></thead><tbody>'+(d.items||[]).map(x=>'<tr><td>'+x.id_endorse+' / '+esc(x.purpose)+'</td><td>'+esc(x.platform)+'</td><td>'+esc(x.status)+'</td><td>'+x.attempts+'</td><td>'+esc(x.created_at)+'</td><td>'+esc(x.error_message||'')+'</td></tr>').join('')+'</tbody></table>'; $('#diagRunBody').html(h); if(!modal) modal=new bootstrap.Modal(document.getElementById('diagRunModal')); modal.show(); }); });
 $('#diagReload,#diagRange').on('click change',load); load();
})();
</script>
