CREATE TABLE `endorse_campaign` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pic` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `spv` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `desc` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `media_file` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Filename of uploaded media (photo or video)',
  `media_type` enum('image','video') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type of media file',
  `date` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budget` double NOT NULL,
  `product` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_text` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `count_influencer` int NOT NULL,
  `count_endorse` int NOT NULL,
  `views` int NOT NULL,
  `likes` int NOT NULL,
  `comment` int NOT NULL,
  `share_save` int NOT NULL,
  `cpm` double NOT NULL,
  `start_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `until_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_cost` double NOT NULL,
  `count_influencer_active` int NOT NULL,
  `count_endorse_active` int NOT NULL,
  `count_influencer_processed` int NOT NULL,
  `count_endorse_processed` int NOT NULL,
  `sync_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_internal` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `endorse_campaign_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_endorse` int NOT NULL,
  `id_campaign` int NOT NULL,
  `date` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `views_before` int NOT NULL,
  `likes_before` int NOT NULL,
  `comment_before` int NOT NULL,
  `share_save_before` int NOT NULL,
  `cpm_before` double NOT NULL,
  `views` int NOT NULL,
  `likes` int NOT NULL,
  `comment` int NOT NULL,
  `share_save` int NOT NULL,
  `cpm` double NOT NULL,
  `views_after` int NOT NULL,
  `likes_after` int NOT NULL,
  `comment_after` int NOT NULL,
  `share_save_after` int NOT NULL,
  `cpm_after` double NOT NULL,
  `total_cost` double NOT NULL,
  `influencer` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ce_before` int NOT NULL,
  `ce_now` int NOT NULL,
  `ce_after` int NOT NULL,
  `ci_before` int NOT NULL,
  `ci_now` int NOT NULL,
  `ci_after` int NOT NULL,
  `ce_active_before` int NOT NULL,
  `ce_active_now` int NOT NULL,
  `ce_active_after` int NOT NULL,
  `ci_active_before` int NOT NULL,
  `ci_active_now` int NOT NULL,
  `ci_active_after` int NOT NULL,
  `ce_processed_before` int NOT NULL,
  `ce_processed_now` int NOT NULL,
  `ce_processed_after` int NOT NULL,
  `ci_processed_before` int NOT NULL,
  `ci_processed_now` int NOT NULL,
  `ci_processed_after` int NOT NULL,
  `is_cron` int NOT NULL,
  `sync_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

