CREATE TABLE `endorse` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_campaign` int NOT NULL,
  `tgl_tf` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tgl_upload` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_endorse` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_payment` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pengajuan_status_payment` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_payment_bundling` tinyint(1) DEFAULT NULL,
  `pengajuan_payment_logs` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `keterangan_payment` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_creator` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pic_text` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_text` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `desc` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pertimbangan` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_brief` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_mou` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_generated_mou` tinyint(1) DEFAULT NULL,
  `link_generated_mou` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rc_endorse` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hppproduk` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `no_rekening` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tgl_remind` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tgl_evaluasi` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_upload` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `code_boost` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `evaluasi_deskriptif` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `views` int NOT NULL,
  `likes` int NOT NULL,
  `comment` int NOT NULL,
  `share_save` int NOT NULL,
  `direct_purchases` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cost_per_1000_impression` double NOT NULL,
  `return_of_interest` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_cost` double NOT NULL,
  `nominal_pengajuan` decimal(15,2) DEFAULT NULL,
  `nominal_dibayarkan` decimal(15,2) DEFAULT NULL,
  `pic` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `influencer` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpm` double NOT NULL,
  `created_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_completeness` enum('complete','partial') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_fields` json DEFAULT NULL,
  `stats_source` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_observed_at` datetime(6) DEFAULT NULL,
  `updated_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bukti_tf` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_telegram` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_campaign` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `task` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `posting_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sync_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_fyp` int NOT NULL,
  `fyp_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `barang_dikirim_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rencana_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kode_ads` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logs` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `media_attachment` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Image or video file path',
  `category_kol` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Category KOL (Niche)',
  `created_at_date` date GENERATED ALWAYS AS ((case when ((`created_at` is null) or (trim(`created_at`) = _utf8mb4'')) then NULL when (char_length(`created_at`) >= 10) then str_to_date(left(`created_at`,10),_utf8mb3'%Y-%m-%d') else NULL end)) STORED,
  `posting_at_date` date GENERATED ALWAYS AS ((case when ((`posting_at` is null) or (trim(`posting_at`) = _utf8mb4'')) then NULL when (char_length(`posting_at`) >= 10) then str_to_date(left(`posting_at`,10),_utf8mb3'%Y-%m-%d') else NULL end)) STORED,
  `rencana_at_date` date GENERATED ALWAYS AS ((case when ((`rencana_at` is null) or (trim(`rencana_at`) = _utf8mb4'')) then NULL when (char_length(`rencana_at`) >= 10) then str_to_date(left(`rencana_at`,10),_utf8mb3'%Y-%m-%d') else NULL end)) STORED,
  `tgl_tf_date` date GENERATED ALWAYS AS ((case when ((`tgl_tf` is null) or (trim(`tgl_tf`) = _utf8mb4'')) then NULL when (char_length(`tgl_tf`) >= 10) then str_to_date(left(`tgl_tf`,10),_utf8mb3'%Y-%m-%d') else NULL end)) STORED,
  `like_initial` int DEFAULT NULL,
  `comment_initial` int DEFAULT NULL,
  `share_initial` int DEFAULT NULL,
  `save_initial` int DEFAULT NULL,
  `view_initial` int DEFAULT NULL,
  `initial_fetched_at` datetime DEFAULT NULL,
  `like_final` int DEFAULT NULL,
  `comment_final` int DEFAULT NULL,
  `share_final` int DEFAULT NULL,
  `save_final` int DEFAULT NULL,
  `view_final` int DEFAULT NULL,
  `final_fetched_at` datetime DEFAULT NULL,
  `like_growth` int DEFAULT NULL,
  `comment_growth` int DEFAULT NULL,
  `share_growth` int DEFAULT NULL,
  `save_growth` int DEFAULT NULL,
  `view_growth` int DEFAULT NULL,
  `request_date` date DEFAULT NULL,
  `request_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_keyword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `optimization_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_optimization` tinyint(1) NOT NULL DEFAULT '0',
  `manual_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `threads_media_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_category_kol` (`category_kol`),
  KEY `idx_endorse_campaign_influencer` (`id_campaign`,`influencer`),
  KEY `idx_endorse_campaign_is_fyp` (`id_campaign`,`is_fyp`),
  KEY `idx_endorse_campaign_created_at` (`id_campaign`,`created_at`),
  KEY `idx_endorse_campaign_rencana_at` (`id_campaign`,`rencana_at`),
  KEY `idx_endorse_campaign_posting_at` (`id_campaign`,`posting_at`),
  KEY `idx_endorse_campaign_tgl_tf` (`id_campaign`,`tgl_tf`),
  KEY `idx_endorse_brand_platform_campaign` (`brand`,`platform`,`id_campaign`),
  KEY `idx_endorse_campaign_status_endorse` (`id_campaign`,`status_endorse`),
  KEY `idx_endorse_campaign_status_payment` (`id_campaign`,`status_payment`),
  KEY `idx_campaign_status` (`id_campaign`,`status`,`status_campaign`),
  KEY `idx_endorse_created_at_date` (`created_at_date`),
  KEY `idx_endorse_posting_at_date` (`posting_at_date`),
  KEY `idx_endorse_rencana_at_date` (`rencana_at_date`),
  KEY `idx_endorse_tgl_tf_date` (`tgl_tf_date`),
  KEY `idx_endorse_product` (`product`),
  KEY `idx_endorse_pic` (`pic`),
  KEY `idx_optimization` (`is_optimization`,`optimization_status`),
  KEY `idx_status_sync` (`status`,`status_campaign`,`sync_at`),
  KEY `idx_endorse_posting_at` (`posting_at`),
  KEY `idx_endorse_campaign_pic` (`id_campaign`,`pic`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `endorse_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_endorse` int NOT NULL,
  `id_campaign` int NOT NULL,
  `date` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `views_before` int NOT NULL,
  `likes_before` int NOT NULL,
  `comment_before` int NOT NULL,
  `share_save_before` int NOT NULL,
  `cpm_before` double NOT NULL,
  `views` int NOT NULL,
  `likes` int NOT NULL,
  `comment` int NOT NULL,
  `share_save` int NOT NULL,
  `cpm` double NOT NULL,
  `views_after` int NOT NULL,
  `likes_after` int NOT NULL,
  `comment_after` int NOT NULL,
  `share_save_after` int NOT NULL,
  `cpm_after` double NOT NULL,
  `total_cost` double NOT NULL,
  `influencer` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_completeness` enum('complete','partial') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_fields` json DEFAULT NULL,
  `stats_source` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stats_observed_at` datetime(6) DEFAULT NULL,
  `updated_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_campaign` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_upload` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_cron` int NOT NULL,
  `sync_at` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `log_date` date GENERATED ALWAYS AS ((case when ((`date` is null) or (trim(`date`) = _utf8mb4'')) then NULL when (char_length(`date`) >= 10) then str_to_date(left(`date`,10),_utf8mb3'%Y-%m-%d') else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_endorse_logs_endorse_date` (`id_endorse`,`date`),
  KEY `idx_endorse_logs_endorse_date_views` (`id_endorse`,`date`,`views_after`),
  KEY `idx_endorse_logs_campaign` (`id_campaign`) /*!80000 INVISIBLE */,
  KEY `idx_endorse_logs_campaign_date` (`id_campaign`,`date`),
  KEY `idx_endorse_logs_endorse_date` (`id_endorse`,`date`) /*!80000 INVISIBLE */,
  KEY `idx_endorse_logs_date_endorse` (`date`,`id_endorse`),
  KEY `idx_id_endorse_date` (`id_endorse`,`date`) /*!80000 INVISIBLE */,
  KEY `idx_endorse_logs_log_date_endorse` (`log_date`,`id_endorse`),
  KEY `idx_endorse_logs_endorse_log_date` (`id_endorse`,`log_date`),
  KEY `idx_campaign_date` (`id_campaign`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

